baseURL = "/"
languageCode = "en-us"
title = "Rob Hogarth's Portfolio Website"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Rob Hogarth, IT Manager"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "rob@robhogarth.com"
    facebook = "robhogarth"
    twitter = "robhogarth"
    linkedin = "https://www.linkedin.com/in/rob-hogarth-5a19151/"


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Rob, a IT Manager and Business Analyst based in Central and Far West NSW."
    hero_right = ["**Currently doing consultancy work at Monpearte IT Solutions. Previously working at Peak Gold Mines as a Senior IT Officer.**", "I am passoinate about making IT departments bring real benefits and change through continual innovation of bussiness processes and workflows"]
    resume = "robhogarth_resume.docx"

[params.footer]
    enable = true
