baseURL = "/"
languageCode = "en-us"
title = "Rob Hogarth's Portfolio Website"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Rob Hogarth, IT Manager"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "robhogarth@gmail.com"
    linkedin = "https://www.linkedin.com/in/rob-hogarth-5a19151/"


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi, I'm Rob Hogarth, an IT Manager based in Central NSW"
    hero_right = ["**Currently doing consultancy work at Monpearte IT Solutions. Previously working at Peak Gold Mines as a Senior IT Officer.**", "I am passionate about making IT departments bring real benefits and change through continual innovation of business processes and workflows.", "I have delivered long and short term strategy in multiple organisations, providing business integrated IT strategy.  This has included creating and executing year on year hardware and software lifecycle planning, infrastructure and application project planning and delivery, as well as budget planning with proven cost consolidation and reduction. I have implemented service catalogs and implemented IT governance frameworks.  I have led teams as well as been part of larger senior leadership teams within businesses.  I am a collaborative leader and work closely with direct reports and my peers to ensure that IT is delivered seamlessly and effectively to a business.  I have a strong focus on mentoring and guiding my direct reports to ensure they develop to their maximum potential.  I have helped to guide staff through directed training to improve their technical, inter-personal and leadership skills with great results." ,"My background is in Windows server and infrastructure including Servers, Storage and Networking.  I have worked in large enterprise systems as well as startups and MSPs focused on small to medium sized businesses.  I have a broad range of experience in numerous technologies including Microsoft server and applications solutions including Windows 10 and Server 2016, Azure and Office365, SharePoint, SQL, Exchange and the System Center Suite.  I have work with numerous storage providers including Dell/EMC, IBM and HP.  I have experience with networking technologies from Cisco, HP, Sonicwall and Palo Alto.  My experience in programming has primarily been focused on the C# development platform working with Windows applications as well as Windows IOT and ASP.NET projects"]
    resume = "robhogarth_resume.docx"

[params.footer]
    enable = true
